### ISSUE TITLE
publishing on hex

### ISSUE THREAD

**Issue by fcevado** [WarpEngineer/geminic#1]
any plans on publishing this on hex?
https://hex.pm/docs/rebar3_publish

**Comment by WarpEngineer** [comment]
I wasn't thinking about it since I add all my rebar deps directly from GitHub, but I have no problems with doing that.  I'll put it on my to-do list.  Just out of curiosity though, what's the advantage of putting it there over just using it straight out of GitHub?

**Comment by fcevado** [comment]
I guess the main thing is to be easily searchable. Besides that, there is the possibility to handle versioning more easily, deprecating old versions and all that.

**Comment by WarpEngineer** [comment]
Oh, that's a good point on making it easily searchable.

**Comment by WarpEngineer** [comment]
This is now published on hex.
